import eventlet
eventlet.monkey_patch()

from flask import Flask, request, session
from flask_socketio import SocketIO, emit, join_room
import os

from database.db_manager import init_db
from routes.views import views_bp
from routes.api import api_bp, DEVICE_TARGET_STATES, DEVICE_LAST_TELEMETRY, DEVICE_LAST_PULL
from routes.auth import auth_bp

def create_app():
    """Application factory for SolarSync AI IoT Dashboard."""
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'solarsync_secure_production_secret_key_89234891')
    app.config['SESSION_COOKIE_HTTPONLY'] = True
    app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'
    
    # Initialize and seed database if not already populated
    init_db()
    
    # Initialize SocketIO with eventlet async mode
    socketio = SocketIO(app, cors_allowed_origins="*", async_mode='eventlet')
    
    # Register blueprints
    app.register_blueprint(auth_bp)
    app.register_blueprint(views_bp)
    app.register_blueprint(api_bp)
    
    # SocketIO Event Handlers
    @socketio.on('connect')
    def handle_connect():
        device_id = session.get('pump_device_id', 'PUMP-SOLAR-1001')
        print(f"Web client connected for device: {device_id}")
        
        target = DEVICE_TARGET_STATES.get(device_id, 0)
        latest = DEVICE_LAST_TELEMETRY.get(device_id, {
            "voltage": 0.0,
            "current": 0.0,
            "power": 0.0,
            "pump_status": 0,
            "runtime": 0.0,
            "energy": 0.0,
            "last_updated": None
        })
        
        # Send current system status to initializing client
        socketio.emit('status_update', {
            "pump_device_id": device_id,
            "target_status": target,
            "latest_telemetry": latest
        }, to=request.sid)
        
    @socketio.on('disconnect')
    def handle_disconnect():
        print("Web client disconnected from SocketIO.")

    @socketio.on('pump_control')
    def handle_pump_control(data):
        """Receives controls commands from dashboard clients for a specific pump."""
        device_id = data.get('pump_device_id') or session.get('pump_device_id', 'PUMP-SOLAR-1001')
        target = int(data.get('target_status', 0))
        print(f"SocketIO: Pump control request for {device_id} -> {target}")
        
        # Update target state globally in API dictionaries
        DEVICE_TARGET_STATES[device_id] = target
        
        # Broadcast the command to all listening clients
        socketio.emit('pump_command', {
            "pump_device_id": device_id,
            "target_status": target
        })
        
        status_text = "STARTED (ON)" if target == 1 else "STOPPED (OFF)"
        socketio.emit('toast', {
            "type": "success" if target == 1 else "info",
            "message": f"Pump signal {status_text} sent for {device_id}."
        })

    @socketio.on('simulated_telemetry')
    def handle_simulated_telemetry(data):
        """Receives mock telemetry generated by browser simulator."""
        from datetime import datetime
        from models.pump_data import insert_reading
        
        device_id = data.get('pump_device_id') or session.get('pump_device_id', 'PUMP-SOLAR-1001')
        
        try:
            voltage = float(data.get('voltage', 0.0))
            current = float(data.get('current', 0.0))
            power = float(data.get('power', 0.0))
            status = int(data.get('pump_status', 0))
            runtime = float(data.get('runtime', 0.0))
            energy = float(data.get('energy', 0.0))
            
            # Write reading directly to database scoped to this pump device
            insert_reading(voltage, current, power, status, runtime, energy, pump_device_id=device_id)
            
            # Update cache
            now_time = datetime.now()
            DEVICE_LAST_TELEMETRY[device_id] = {
                "voltage": round(voltage, 2),
                "current": round(current, 2),
                "power": round(power, 2),
                "pump_status": status,
                "runtime": round(runtime, 4),
                "energy": round(energy, 4),
                "last_updated": now_time.strftime('%H:%M:%S')
            }
            DEVICE_LAST_PULL[device_id] = now_time
            
            # Broadcast update
            target_status = DEVICE_TARGET_STATES.get(device_id, 0)
            socketio.emit('telemetry', {
                **DEVICE_LAST_TELEMETRY[device_id],
                "pump_device_id": device_id,
                "esp32_online": True,
                "target_status": target_status
            })
            
        except Exception as e:
            print(f"Error in SocketIO simulated telemetry receiver: {e}")

    return app, socketio

# Module-level instances for WSGI/Gunicorn servers
app, socketio = create_app()

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    print(f"Starting SolarSync AI Multi-Customer Server on http://0.0.0.0:{port} ...")
    socketio.run(app, host='0.0.0.0', port=port, debug=False)
